-- Seed fandom/artist metadata for hosts present in the Stationhead weekly leaderboard
-- captured 2026-09-23. Hosts without sufficiently reliable public attribution are intentionally
-- left absent so Pages renders `—` instead of guessing.
--
-- Unresolved from the current top 100:
-- bluee802, wondubu, thenabstreamsofc, keisan13, leeleowon2531, aeraaa01, mome8

INSERT INTO sh_channel_fandoms(
  host_name, artist_name, relation_type, source_url, source_note, verified_at
) VALUES
  ('sixtonessme', 'SixTONES', 'official', 'https://app.stationhead.com/sixtonessme', 'Official artist/label Stationhead identity confirmed from public official announcements.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('st05010121', 'SixTONES', 'fandom', 'https://stationhead.com/st05010121', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('milkofficial', 'M!LK', 'official', 'https://sd-milk.com/contents/1012279', 'Official artist/label Stationhead identity confirmed from public official announcements.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('btskkul0613fm', 'BTS', 'fandom', 'https://stationhead.com/btskkul0613fm', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('jo1ranking2', 'JO1', 'fandom', 'https://stationhead.com/jo1ranking2', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('numberiradio', 'Number_i', 'fandom', 'https://stationhead.com/numberiradio', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('megrokosmos25', 'BTS', 'fandom', 'https://stationhead.com/megrokosmos25', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('jo1official', 'JO1', 'official', 'https://jo1.jp/news/detail/6377', 'Official artist/label Stationhead identity confirmed from public official announcements.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('aegroup0515', 'Aぇ! group', 'official', 'https://stationhead.com/aegroup0515', 'Official artist/label Stationhead identity confirmed from public official announcements.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('makitk33', 'SixTONES', 'fandom', 'https://stationhead.com/makitk33', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('befirstofficial', 'BE:FIRST', 'official', 'https://stationhead.com/befirstofficial', 'Official artist/label Stationhead identity confirmed from public official announcements.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('sakanactionjp', 'サカナクション', 'official', 'https://sakanaction.jp/news/detail/2960', 'Official artist/label Stationhead identity confirmed from public official announcements.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('jo1ranking3', 'JO1', 'fandom', 'https://stationhead.com/jo1ranking3', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('kpsupport', 'King & Prince', 'fandom', 'https://stationhead.com/kpsupport', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('evxntracks', 'EVAN', 'fandom', 'https://stationhead.com/evxntracks', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('evanofficial', 'EVAN', 'official', 'https://stationhead.com/evanofficial', 'Official artist Stationhead identity identified from public artist/fandom references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('enhypenjapanfb', 'ENHYPEN', 'fandom', 'https://stationhead.com/enhypenjapanfb', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('btspainradio', 'BTS', 'fandom', 'https://stationhead.com/btspainradio', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('6stonesshin', 'SixTONES', 'fandom', 'https://stationhead.com/6stonesshin', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('inistreaming', 'INI', 'fandom', 'https://stationhead.com/inistreaming', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('stayonair', 'Stray Kids', 'fandom', 'https://stationhead.com/stayonair', 'Target identified from the public STAYS Stationhead channel.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('nnstation', 'NINGNING', 'fandom', 'https://stationhead.com/nnstation', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('milagrogramz', 'Nicki Minaj', 'fandom', 'https://stationhead.com/milagrogramz', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('karinastation', 'KARINA', 'fandom', 'https://stationhead.com/karinastation', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('karinalands', 'KARINA', 'fandom', 'https://stationhead.com/karinalands', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('markleevotingth', 'MARK', 'fandom', 'https://stationhead.com/markleevotingth', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('mkleeph', 'MARK', 'fandom', 'https://stationhead.com/mkleeph', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('evanwave', 'EVAN', 'fandom', 'https://stationhead.com/evanwave', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('enstationhead', 'ENHYPEN', 'fandom', 'https://stationhead.com/enstationhead', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('engeneuniversity', 'ENHYPEN', 'fandom', 'https://stationhead.com/engeneuniversity', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('hamadaction', 'サカナクション', 'fandom', 'https://stationhead.com/hamadaction', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('bestycentral', 'BE:FIRST', 'fandom', 'https://stationhead.com/bestycentral', 'Target identified from the public BESTY Stationhead channel.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('bumpofchicken', 'BUMP OF CHICKEN', 'official', 'https://www.bumpofchicken.com/news/news/3638', 'Official Stationhead account confirmed by BUMP OF CHICKEN official site.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('pocketzstation', 'ENHYPEN', 'fandom', 'https://stationhead.com/pocketzstation', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('ministreaming', 'INI', 'fandom', 'https://stationhead.com/ministreaming', 'Target identified from public MINI/INI streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('andteamststation', '&TEAM', 'fandom', 'https://stationhead.com/andteamststation', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('rsstationhead', 'ROSÉ', 'fandom', 'https://stationhead.com/rsstationhead', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('moastation', 'TOMORROW X TOGETHER', 'fandom', 'https://stationhead.com/moastation', 'Target identified from public MOA/TXT Stationhead references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('snowmanfan9sima', 'Snow Man', 'fandom', 'https://stationhead.com/snowmanfan9sima', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('lesserafim', 'LE SSERAFIM', 'official', 'https://stationhead.com/lesserafim', 'Official artist Stationhead account confirmed from public official announcements.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('number1station', 'Number_i', 'fandom', 'https://stationhead.com/number1station', 'Target identified from public iLYs/Number_i Stationhead references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('enhypenupdates', 'ENHYPEN', 'fandom', 'https://stationhead.com/enhypenupdates', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('moalympics', 'TOMORROW X TOGETHER', 'fandom', 'https://stationhead.com/moalympics', 'Target identified from public MOA/TXT Stationhead references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('teamiespotify', '&TEAM', 'fandom', 'https://stationhead.com/teamiespotify', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('stationplave2', 'PLAVE', 'fandom', 'https://stationhead.com/stationplave2', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('teamwinterdc', 'WINTER', 'fandom', 'https://stationhead.com/teamwinterdc', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('applemusicv', 'V', 'fandom', 'https://stationhead.com/applemusicv', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('ald1streaming', 'ALPHA DRIVE ONE', 'fandom', 'https://stationhead.com/ald1streaming', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('sb19station', 'SB19', 'fandom', 'https://stationhead.com/sb19station', 'Target identified from public ATIN/SB19 Stationhead references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('enstationid', 'ENHYPEN', 'fandom', 'https://stationhead.com/enstationid', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('casstieljeon', 'Jung Kook', 'fandom', 'https://stationhead.com/casstieljeon', 'Target identified from public Stationhead/X/Jung Kook fan references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('plaveintl', 'PLAVE', 'fandom', 'https://stationhead.com/plaveintl', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('plaveintlsp1', 'PLAVE', 'fandom', 'https://stationhead.com/plaveintlsp1', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('stayworld', 'Stray Kids', 'fandom', 'https://stationhead.com/stayworld', 'Target identified from public STAYS/Stray Kids Stationhead references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('andteamstation', '&TEAM', 'fandom', 'https://stationhead.com/andteamstation', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('radiowinter', 'WINTER', 'fandom', 'https://stationhead.com/radiowinter', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('17stationhead', 'SEVENTEEN', 'fandom', 'https://stationhead.com/17stationhead', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('lywstationhead', 'Lim Young Woong', 'fandom', 'https://stationhead.com/lywstationhead', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('jmxxxla', 'Jimin', 'fandom', 'https://stationhead.com/jmxxxla', 'Target identified from public Stationhead/X/Jimin fan references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('busofficial', 'BUS because of you i shine', 'official', 'https://stationhead.com/busofficial', 'Official artist Stationhead account identified from BUS official public posts.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('maxxhaxxyx523kp', 'King & Prince', 'fandom', 'https://stationhead.com/maxxhaxxyx523kp', 'Target identified from public King & Prince support references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('andteamaze', '&TEAM', 'fandom', 'https://stationhead.com/andteamaze', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('markleestrm', 'MARK', 'fandom', 'https://stationhead.com/markleestrm', 'Target identified from public Stationhead/X/Mark streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('maki0214', 'MAKI', 'fandom', 'https://stationhead.com/maki0214', 'Target identified from public MAKI support references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('vipvnteam', 'BIGBANG', 'fandom', 'https://stationhead.com/vipvnteam', 'Target identified from public VIP/BIGBANG streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('vipsociety2006', 'BIGBANG', 'fandom', 'https://stationhead.com/vipsociety2006', 'Target identified from public VIP/BIGBANG streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('peemwasuth', 'PEEMWASU', 'fandom', 'https://stationhead.com/peemwasuth', 'Target identified from public PEEMWASU fanbase references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('jungwonvoting', 'JUNGWON', 'fandom', 'https://stationhead.com/jungwonvoting', 'Target identified from public Stationhead/X/JUNGWON support references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('hellophuongtuan', 'Jack - J97', 'fandom', 'https://stationhead.com/hellophuongtuan', 'Target identified from public Jack - J97 fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('taestationjp', 'V', 'fandom', 'https://stationhead.com/taestationjp', 'Target identified from public Stationhead/X/V streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('sb19usatin', 'SB19', 'fandom', 'https://stationhead.com/sb19usatin', 'Target identified from public ATIN/SB19 Stationhead references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('lune0926', '&TEAM', 'fandom', 'https://stationhead.com/lune0926', 'Target identified from public LUNÉ/&TEAM streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('pjaystreams', 'JAY', 'fandom', 'https://stationhead.com/pjaystreams', 'Target identified from public JAY support references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('tomoru0307', 'King & Prince', 'fandom', 'https://stationhead.com/tomoru0307', 'Target identified from public King & Prince Stationhead references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('tetehome', 'V', 'fandom', 'https://stationhead.com/tetehome', 'Target identified from public Stationhead/X/V streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('onlyjack97', 'Jack - J97', 'fandom', 'https://stationhead.com/onlyjack97', 'Target identified from public Jack - J97 fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('lywradio', 'Lim Young Woong', 'fandom', 'https://stationhead.com/lywradio', 'Target identified from public Stationhead/X/fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('sbesties', 'SB19', 'fandom', 'https://stationhead.com/sbesties', 'Target identified from the public ATIN Stationhead channel.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('kitayamaofficial', '北山宏光', 'official', 'https://redon-official.jp/news/ultra-digital/', 'Official Stationhead account confirmed by RED ON official site.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('jisoostreamingg', 'JISOO', 'fandom', 'https://stationhead.com/jisoostreamingg', 'Target identified from public Stationhead/X/JISOO streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('madnaejin', 'JIN', 'fandom', 'https://stationhead.com/madnaejin', 'Target identified from public Stationhead/X/JIN fan references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('j97spotify', 'Jack - J97', 'fandom', 'https://stationhead.com/j97spotify', 'Target identified from public Jack - J97 fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('tenleeteam', 'TEN', 'fandom', 'https://stationhead.com/tenleeteam', 'Target identified from public Stationhead/X/TEN fan references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('hoshimachisuisei', '星街すいせい', 'official', 'https://stationhead.com/hoshimachisuisei', 'Official Studio STELLAR listening-party identity for Hoshimachi Suisei.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('5kingsstronghold', 'SB19', 'fandom', 'https://stationhead.com/5kingsstronghold', 'Target identified from public ATIN/SB19 Stationhead references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('jungkookstation', 'Jung Kook', 'fandom', 'https://stationhead.com/jungkookstation', 'Target identified from public Jung Kook streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('frombaseone', 'ZEROBASEONE', 'fandom', 'https://stationhead.com/frombaseone', 'Target identified from public ZEROBASEONE fandom streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('jiminrecord13', 'Jimin', 'fandom', 'https://stationhead.com/jiminrecord13', 'Target identified from public Jimin streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('jacksonwstream', 'Jackson Wang', 'fandom', 'https://stationhead.com/jacksonwstream', 'Target identified from public Jackson Wang streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('yeondreamfm', 'YEONJUN', 'fandom', 'https://stationhead.com/yeondreamfm', 'Target identified from public YEONJUN streaming references.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('kumakp', 'King & Prince', 'fandom', 'https://stationhead.com/kumakp', 'Target identified from public King & Prince Stationhead/fandom context.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('yxxjxny', 'YEONJUN', 'fandom', 'https://stationhead.com/yxxjxny', 'Target identified from public YEONJUN fandom context.', CAST(strftime('%s', 'now') AS INTEGER) * 1000),
  ('minitimestation', 'INI', 'fandom', 'https://stationhead.com/minitimestation', 'Target identified from public MINI/INI Stationhead context.', CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(host_name) DO UPDATE SET
  artist_name = excluded.artist_name,
  relation_type = excluded.relation_type,
  source_url = excluded.source_url,
  source_note = excluded.source_note,
  verified_at = excluded.verified_at;
