-- Retire regional providers that are no longer collected or exposed.
DELETE FROM regional_music_playlist_memberships WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
DELETE FROM regional_music_playlist_snapshots WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
DELETE FROM regional_music_playlists WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
DELETE FROM regional_music_artist_track_order WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
DELETE FROM regional_music_track_daily WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
DELETE FROM regional_music_tracks WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
DELETE FROM regional_music_releases WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
DELETE FROM regional_music_artist_daily WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
DELETE FROM regional_music_artist_profiles WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
DELETE FROM regional_music_collector_state WHERE service IN ('genie','bugs','joox','nhaccuatui','anghami','melon','netease_cloud_music','naver_vibe','flo','yandex_music','boomplay','plern','fungjai','zing_mp3','jiosaavn','gaana','langit_musik');
